from copy import copy

AUDIO_FUNCTIONALS_EGEMAPS_V2_COLS = ['F0semitoneFrom27.5Hz_sma3nz_amean',
                                     'F0semitoneFrom27.5Hz_sma3nz_stddevNorm',
                                     'F0semitoneFrom27.5Hz_sma3nz_percentile20.0',
                                     'F0semitoneFrom27.5Hz_sma3nz_percentile50.0',
                                     'F0semitoneFrom27.5Hz_sma3nz_percentile80.0',
                                     'F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2',
                                     'F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope',
                                     'F0semitoneFrom27.5Hz_sma3nz_stddevRisingSlope',
                                     'F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope',
                                     'F0semitoneFrom27.5Hz_sma3nz_stddevFallingSlope', 'loudness_sma3_amean',
                                     'loudness_sma3_stddevNorm', 'loudness_sma3_percentile20.0',
                                     'loudness_sma3_percentile50.0', 'loudness_sma3_percentile80.0',
                                     'loudness_sma3_pctlrange0-2', 'loudness_sma3_meanRisingSlope',
                                     'loudness_sma3_stddevRisingSlope', 'loudness_sma3_meanFallingSlope',
                                     'loudness_sma3_stddevFallingSlope', 'spectralFlux_sma3_amean',
                                     'spectralFlux_sma3_stddevNorm', 'mfcc1_sma3_amean',
                                     'mfcc1_sma3_stddevNorm', 'mfcc2_sma3_amean', 'mfcc2_sma3_stddevNorm',
                                     'mfcc3_sma3_amean', 'mfcc3_sma3_stddevNorm', 'mfcc4_sma3_amean',
                                     'mfcc4_sma3_stddevNorm', 'jitterLocal_sma3nz_amean',
                                     'jitterLocal_sma3nz_stddevNorm', 'shimmerLocaldB_sma3nz_amean',
                                     'shimmerLocaldB_sma3nz_stddevNorm', 'HNRdBACF_sma3nz_amean',
                                     'HNRdBACF_sma3nz_stddevNorm', 'logRelF0-H1-H2_sma3nz_amean',
                                     'logRelF0-H1-H2_sma3nz_stddevNorm', 'logRelF0-H1-A3_sma3nz_amean',
                                     'logRelF0-H1-A3_sma3nz_stddevNorm', 'F1frequency_sma3nz_amean',
                                     'F1frequency_sma3nz_stddevNorm', 'F1bandwidth_sma3nz_amean',
                                     'F1bandwidth_sma3nz_stddevNorm', 'F1amplitudeLogRelF0_sma3nz_amean',
                                     'F1amplitudeLogRelF0_sma3nz_stddevNorm', 'F2frequency_sma3nz_amean',
                                     'F2frequency_sma3nz_stddevNorm', 'F2bandwidth_sma3nz_amean',
                                     'F2bandwidth_sma3nz_stddevNorm', 'F2amplitudeLogRelF0_sma3nz_amean',
                                     'F2amplitudeLogRelF0_sma3nz_stddevNorm', 'F3frequency_sma3nz_amean',
                                     'F3frequency_sma3nz_stddevNorm', 'F3bandwidth_sma3nz_amean',
                                     'F3bandwidth_sma3nz_stddevNorm', 'F3amplitudeLogRelF0_sma3nz_amean',
                                     'F3amplitudeLogRelF0_sma3nz_stddevNorm', 'alphaRatioV_sma3nz_amean',
                                     'alphaRatioV_sma3nz_stddevNorm', 'hammarbergIndexV_sma3nz_amean',
                                     'hammarbergIndexV_sma3nz_stddevNorm', 'slopeV0-500_sma3nz_amean',
                                     'slopeV0-500_sma3nz_stddevNorm', 'slopeV500-1500_sma3nz_amean',
                                     'slopeV500-1500_sma3nz_stddevNorm', 'spectralFluxV_sma3nz_amean',
                                     'spectralFluxV_sma3nz_stddevNorm', 'mfcc1V_sma3nz_amean',
                                     'mfcc1V_sma3nz_stddevNorm', 'mfcc2V_sma3nz_amean',
                                     'mfcc2V_sma3nz_stddevNorm', 'mfcc3V_sma3nz_amean',
                                     'mfcc3V_sma3nz_stddevNorm', 'mfcc4V_sma3nz_amean',
                                     'mfcc4V_sma3nz_stddevNorm', 'alphaRatioUV_sma3nz_amean',
                                     'hammarbergIndexUV_sma3nz_amean', 'slopeUV0-500_sma3nz_amean',
                                     'slopeUV500-1500_sma3nz_amean', 'spectralFluxUV_sma3nz_amean',
                                     'loudnessPeaksPerSec', 'VoicedSegmentsPerSec',
                                     'MeanVoicedSegmentLengthSec', 'StddevVoicedSegmentLengthSec',
                                     'MeanUnvoicedSegmentLength', 'StddevUnvoicedSegmentLength',
                                     'equivalentSoundLevel_dBp']

new_features = ["CumPauseLength",
                "MeanPauseSegmentLength",
                "PausesAbove0.5Sec",
                "PausesAbove1Sec",
                "PausesAbove1.5Sec",
                "PausesAbove2Sec"]

AUDIO_FUNCTIONALS_EGEMAPS_V2_COLS_NEW_FEATURES = copy(AUDIO_FUNCTIONALS_EGEMAPS_V2_COLS)
AUDIO_FUNCTIONALS_EGEMAPS_V2_COLS_NEW_FEATURES.extend(new_features)


var_name_to_feat = {
    # Frequency features
    'F0semitoneFrom27.5Hz_sma3nz_amean': 'F0 M',
    'F0semitoneFrom27.5Hz_sma3nz_stddevNorm': 'F0 CV',
    'F0semitoneFrom27.5Hz_sma3nz_percentile20.0': 'F0 P20',
    'F0semitoneFrom27.5Hz_sma3nz_percentile50.0': 'F0 P50',
    'F0semitoneFrom27.5Hz_sma3nz_percentile80.0': 'F0 P80',
    'F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2': 'F0 P range',
    'F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope': 'F0 M rising slope',
    'F0semitoneFrom27.5Hz_sma3nz_stddevRisingSlope': 'F0 SD rising slope',
    'F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope': 'F0 M falling slope',
    'F0semitoneFrom27.5Hz_sma3nz_stddevFallingSlope': 'F0 SD falling slope',
    'loudness_sma3_amean': 'Loudness M',
    'loudness_sma3_stddevNorm': 'Loudness CV',
    'loudness_sma3_percentile20.0': 'Loudness P20',
    'loudness_sma3_percentile50.0': 'Loudness P50',
    'loudness_sma3_percentile80.0': 'Loudness P80',
    'loudness_sma3_pctlrange0-2': 'Loudness P range',
    'loudness_sma3_meanRisingSlope': 'Loudness M rising slope',
    'loudness_sma3_stddevRisingSlope': 'Loudness SD rising slope',
    'loudness_sma3_meanFallingSlope': 'Loudness M falling slope',
    'loudness_sma3_stddevFallingSlope': 'Loudness SD falling slope',
    'spectralFlux_sma3_amean': 'Spectral flux M',
    'spectralFlux_sma3_stddevNorm': 'Spectral flux CV',
    'mfcc1_sma3_amean': 'MFCC1 M',
    'mfcc1_sma3_stddevNorm': 'MFCC1 CV',
    'mfcc2_sma3_amean': 'MFCC2 M',
    'mfcc2_sma3_stddevNorm': 'MFCC2 CV',
    'mfcc3_sma3_amean': 'MFCC3 M',
    'mfcc3_sma3_stddevNorm': 'MFCC3 CV',
    'mfcc4_sma3_amean': 'MFCC4 M',
    'mfcc4_sma3_stddevNorm': 'MFCC4 CV',
    'jitterLocal_sma3nz_amean': 'Jitter M',
    'jitterLocal_sma3nz_stddevNorm': 'Jitter CV',
    'shimmerLocaldB_sma3nz_amean': 'Shimmer M',
    'shimmerLocaldB_sma3nz_stddevNorm': 'Shimmer CV',
    'HNRdBACF_sma3nz_amean': 'Harmonics to noise ratio M',
    'HNRdBACF_sma3nz_stddevNorm': 'Harmonics to noise ratio CV',
    'logRelF0-H1-H2_sma3nz_amean': 'H1-H2 M',
    'logRelF0-H1-H2_sma3nz_stddevNorm': 'H1-H2 CV',
    'logRelF0-H1-A3_sma3nz_amean': 'H1-A3 M',
    'logRelF0-H1-A3_sma3nz_stddevNorm': 'H1-A3 CV',
    'F1frequency_sma3nz_amean': 'F1 frequency M',
    'F1frequency_sma3nz_stddevNorm': 'F1 frequency CV',
    'F1bandwidth_sma3nz_amean': 'F1 bandwidth M',
    'F1bandwidth_sma3nz_stddevNorm': 'F1 bandwidth CV',
    'F1amplitudeLogRelF0_sma3nz_amean': 'F1 amplitude M',
    'F1amplitudeLogRelF0_sma3nz_stddevNorm': 'F1 amplitude CV',
    'F2frequency_sma3nz_amean': 'F2 frequency M',
    'F2frequency_sma3nz_stddevNorm': 'F2 frequency CV',
    'F2bandwidth_sma3nz_amean': 'F2 bandwidth M',
    'F2bandwidth_sma3nz_stddevNorm': 'F2 bandwidth CV',
    'F2amplitudeLogRelF0_sma3nz_amean': 'F2 amplitude M',
    'F2amplitudeLogRelF0_sma3nz_stddevNorm': 'F2 amplitude CV',
    'F3frequency_sma3nz_amean': 'F3 frequency M',
    'F3frequency_sma3nz_stddevNorm': 'F3 frequency CV',
    'F3bandwidth_sma3nz_amean': 'F3 bandwidth M',
    'F3bandwidth_sma3nz_stddevNorm': 'F3 bandwidth CV',
    'F3amplitudeLogRelF0_sma3nz_amean': 'F3 amplitude M',
    'F3amplitudeLogRelF0_sma3nz_stddevNorm': 'F3 amplitude CV',
    'alphaRatioV_sma3nz_amean': 'Alpha ratio (voiced) M',
    'alphaRatioV_sma3nz_stddevNorm': 'Alpha ratio (voiced) CV',
    'hammarbergIndexV_sma3nz_amean': 'Hammarberg index (voiced) M',
    'hammarbergIndexV_sma3nz_stddevNorm': 'Hammarberg index (voiced) CV',
    'slopeV0-500_sma3nz_amean': 'Spectral slope 0-500 (voiced) M',
    'slopeV0-500_sma3nz_stddevNorm': 'Spectral slope 0-500 (voiced) CV',
    'slopeV500-1500_sma3nz_amean': 'Spectral slope 500-1500 (voiced) M',
    'slopeV500-1500_sma3nz_stddevNorm': 'Spectral slope 500-1500 (voiced) CV',
    'spectralFluxV_sma3nz_amean': 'Spectral flux (voiced) M',
    'spectralFluxV_sma3nz_stddevNorm': 'Spectral flux (voiced) CV',
    'mfcc1V_sma3nz_amean': 'MFCC1 (voiced) M',
    'mfcc1V_sma3nz_stddevNorm': 'MFCC1 (voiced) CV',
    'mfcc2V_sma3nz_amean': 'MFCC2 (voiced) M',
    'mfcc2V_sma3nz_stddevNorm': 'MFCC2 (voiced) CV',
    'mfcc3V_sma3nz_amean': 'MFCC3 (voiced) M',
    'mfcc3V_sma3nz_stddevNorm': 'MFCC3 (voiced) CV',
    'mfcc4V_sma3nz_amean': 'MFCC4 (voiced) M',
    'mfcc4V_sma3nz_stddevNorm': 'MFCC4 (voiced) CV',
    'alphaRatioUV_sma3nz_amean': 'Alpha ratio (unvoiced) M',
    'hammarbergIndexUV_sma3nz_amean': 'Hammarberg index (unvoiced) M',
    'slopeUV0-500_sma3nz_amean': 'Spectral slope 0-500 (unvoiced) M',
    'slopeUV500-1500_sma3nz_amean': 'Spectral slope 500-1500 (unvoiced) M',
    'spectralFluxUV_sma3nz_amean': 'Spectral flux (unvoiced) M',
    'loudnessPeaksPerSec': 'Loudness peaks per second',
    'VoicedSegmentsPerSec': 'Voiced segments per second',
    'MeanVoicedSegmentLengthSec': 'Voiced segment length M',
    'StddevVoicedSegmentLengthSec': 'Voiced segment length CV',
    'MeanUnvoicedSegmentLength': 'Unvoiced segment length M',
    'StddevUnvoicedSegmentLength': 'Unvoiced segment length CV',
    'equivalentSoundLevel_dBp': 'Equivalent sound level M',
    'CumPauseLength': "Cumulative Pause Length",
    'MeanPauseSegmentLength': "Pause Segment Length M",
    'PausesAbove0.5Sec': "Pauses Above 0.5 seconds",
    'PausesAbove1Sec': "Pauses Above 1 second",
    'PausesAbove1.5Sec': "Pauses Above 1.5 seconds",
    'PausesAbove2Sec': "Pauses Above 2 seconds"
}
